### PR TITLE
Re-sectioned the Cookbook to reflect the two-branch structure of the DESC DRP

### PR DESCRIPTION
**Pull request by drphilmarshall**
This was an easy change to make, it turns out - I guess we were already conceptualizing the DRP as two branches, one for the static sky and one for the time domain. I think all four of @nicolaschotard @heather999 @DominiqueFouchez and @SimonKrughoff should review this PR to make sure it makes sense. Thanks!

### CODE REVIEW

**Comment by nicolaschotard** [comment]
This looks good to me. We will now have to update each section. 

Waiting for others to comment before merging.

**Comment by drphilmarshall** [comment]
@DominiqueFouchez @heather999 @johannct Can you please check that the two-branch DRP pipeline described in the Cookbook in this branch is the right way to present, at a high level, the structure of the DRP? It would be good to get this merged one way or another before taking any next steps in documenting the DM DC2 implementation of the DRP pipeline.

**Comment by johannct** [comment]
I will look at it asap (probably at the airport...) One thing I noticed (sorry but I did not pay attention to the cookbook since I took over from Nicolas) is that we are now using the pipeline drivers, so we are not executing the atomistic executables anymore (processCcd is under singleFrameDriver, makeCoaddTempExp and assembleCoadd is under coaddDriver). So this will need attention, likely in another branch that I will have to deal with likely.

**Comment by heather999** [comment]
I agree with the general approach, to have this division.  As @johannct pointed out, a lot of the internal content needs updating due to changes.  I also notice the many of the reference links are not working, possibly due to the conversion from MD to rST.  I'll try fixing those up.

**Pull request merged**
