### PR TITLE
U/heather999/issue 131

### PR DESCRIPTION
**Pull request by heather999**
Should be ready to merge. The primary changes are: 
- setup now includes obs_lsst and DC2-production
- meas_extensions_ngmix was updated to 0.9.5
- GCRCatalogs is now at 0.14.5
- Provided a new constraints file for DM's newer version of conda 4.6.8    

Just a couple of questions for @johannct 
- is the env_config/test file needed?
- There is an echo command in the setup script that returns an error at NERSC - I can either figure out what it needs to be doing, or make it run only if we're not at NERSC.
- If we decide to use 19.0.0 rather than w_2019_47, there will be a need to update the setup script.
- Once the dc2/run2.2 branch of obs_lsst is tagged, that tag should be used in the setup script

### CODE REVIEW

**Comment by johannct** [comment]
the echo prints the DM stack version in a file at the same place as the rest of the setup. The env_config/test is not needed as far as I know. It must have been picked up in a global commit

**Comment by heather999** [comment]
The issue with the echo statement is the syntax.  I see what it is trying to do, but it returns an error:
```echo "${DESC_STACK_VER}" > $1/stack_version```
This would work for me: 
```echo $1/"${DESC_STACK_VER}"```

**Comment by johannct** [comment]
`echo $1/"${DESC_STACK_VER}"` just print it onscreen. I want to capture it as a single line in the file named `stack_version`. This is exactly what it does at CC.

**Comment by heather999** [comment]
Superseded by PR #139

**Pull request closed without merging**
